# Generated by Django 4.1.1 on 2022-09-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
